Mar 21 17:04:46 ansible2 sshd[5576]: Accepted publickey for ansible from 192.168.10.10 port 46876 ssh2: RSA SHA256:n9WE6/qxErd4IznBM1aYfitpBCnyUn1Aks3qHHWwzD4
Mar 21 17:04:46 ansible2 systemd[5582]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Mar 21 17:04:46 ansible2 sshd[5576]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 17:04:50 ansible2 sudo[5830]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lbmukyfxwvyhoxuetqsgfpnubtzgcaie ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679385887.0027833-22145-150620482071528/AnsiballZ_setup.py
Mar 21 17:04:50 ansible2 sudo[5830]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 17:04:50 ansible2 sudo[5830]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 17:04:52 ansible2 sudo[5830]: pam_unix(sudo:session): session closed for user root
Mar 21 17:04:54 ansible2 sudo[6051]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yoinerufdudjrnuhbeztkxvztglctozo ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679385892.6815736-22205-123398992737501/AnsiballZ_slurp.py
Mar 21 17:04:54 ansible2 sudo[6051]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 17:04:54 ansible2 sudo[6051]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
